import Head from 'next/head'
import {BsFillMoonStarsFill, BsLinkedin, BsGithub} from 'react-icons/bs'
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"

// Exporting the function/component called Home as a default
// A component is a JS func that returns some HTML(JSX)
export default function Home() {
  return (
    <div>
      <Head>
        <title>Sameer&apos;s Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          {/* navbar */}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-3xl font-quickKiss'>Sameer</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <a href='https://linkedin.com/in/-sameer/'><BsLinkedin className='text-2xl ml-5 rounded-md'/></a>
              <li><a className='bg-gradient-to-r from-cyan-500 to-purple-400 text-white px-4 py-1.5 rounded-2xl ml-5' href='https://drive.google.com/uc?export=download&id=16d1L187ZgMzFEe3TwRPcAPmBwRlh-s6R'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center'>
            <h2 className='text-5xl text-cyan-500'>Hi,</h2>
            <h2 className='text-2xl font-medium text-cyan-500'>I&apos;m Sameer</h2>
            <h2 className='text-xl text-gray-600 pt-5'>Software Developer</h2>
            <h2 className='text-xl text-gray-600'>and Machine Learning Engineer</h2>
          </div>
          <div className='flex justify-center my-10'>
            <div className='relative bg-gradient-to-b from-cyan-500 to bg-purple-400 rounded-full w-80 h-80 flex items-center overflow-hidden'>
              <Image src={deved} layout="fill" objectFit='cover' />
            </div>
          </div>
        </section>
        <section>
          <div className='text-center md:max-w-3xl mx-auto py-10'>
            <h2 className='text-4xl text-gray-600 font-medium'>About me</h2>
            <p className='text-xl py-3 text-gray-600'>
              I am an expert software developer capable of working with both the <span className='text-cyan-500'>front-end</span> and <span className='text-cyan-500'>backend</span> of applications.
              I create user-friendly, performant <span className='text-cyan-500'>web applications</span> that scale.
              I also do <span className='text-cyan-500'>UI/UX design</span> and have experience working with the <span className='text-cyan-500'>cloud</span>, 
              creating <span className='text-cyan-500'>machine learning</span> models, and <span className='text-cyan-500'>DevOps</span> pipelines.
              Currently pursuing my Bachelor of Computer Engineering degree at Memorial University of Newfoundland.
            </p>
          </div>
          <div>
            <h2 className='text-4xl text-gray-600 pt-10 pb-5 font-medium'>Core Services</h2>
            <div className='text-center'>
              <div className='shadow-lg p-10 rounded-xl'>
                <Image src={design} width={100} height={100}/>
                <h2 className='text-lg'>UI/UX Design</h2>
              </div>
              <div className='shadow-lg p-10 rounded-xl'>
                <Image src={code} width={100} height={100} />
                <h2 className='text-lg'>Software Development</h2>
              </div>
              <div className='shadow-lg p-10 rounded-xl'>
                <Image src={code} width={100} height={100} />
                <h2 className='text-lg'>Machine Learning</h2>
              </div>
            </div>
        </div>
        </section>
        <section>
          <div>
            <h3 className='text-4xl text-gray-600 pt-10 pb-5 font-medium'>Work Experience</h3>
            <p className='text-xl py-3 text-gray-600'>
              I am an expert software developer capable of working with both the <span className='text-cyan-500'>front-end</span> and <span className='text-cyan-500'>backend</span> of applications.
              I create user-friendly, performant <span className='text-cyan-500'>web applications</span> that scale.
              I also do <span className='text-cyan-500'>UI/UX design</span> and have experience working with the <span className='text-cyan-500'>cloud</span>, 
              creating <span className='text-cyan-500'>machine learning</span> models, and <span className='text-cyan-500'>DevOps</span> pipelines.
              Currently pursuing my Bachelor of Computer Engineering degree at Memorial University of Newfoundland.
            </p>
          </div>
          <div>
            <h3 className='text-4xl text-gray-600 pt-10 pb-5 font-medium'>Projects</h3>
            <p className='text-xl py-3 text-gray-600'>
              I am an expert software developer capable of working with both the <span className='text-cyan-500'>front-end</span> and <span className='text-cyan-500'>backend</span> of applications.
              I create user-friendly, performant <span className='text-cyan-500'>web applications</span> that scale.
              I also do <span className='text-cyan-500'>UI/UX design</span> and have experience working with the <span className='text-cyan-500'>cloud</span>, 
              creating <span className='text-cyan-500'>machine learning</span> models, and <span className='text-cyan-500'>DevOps</span> pipelines.
              Currently pursuing my Bachelor of Computer Engineering degree at Memorial University of Newfoundland.
            </p>
          </div>
          <div>
            <div>
              <Image src={web1}/>
            </div>
            <div>
              <Image src={web2}/>
            </div>
            <div>
              <Image src={web3}/>
              <div>
              <Image src={web4}/>
            </div>
            <div>
              <Image src={web5}/>
            </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
