import Head from 'next/head'
import {BsFillMoonStarsFill, BsLinkedin} from 'react-icons/bs'
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import { useState } from 'react'
import Link from 'next/link'

// Exporting the function/component called Home as a default
// A component is a JS func that returns some HTML(JSX)
// State is managed within the component
export default function Home() {
  const [darkMode, setDarkMode]=useState(false)
  return (
    <div className={darkMode ? 'dark':""}>
      <Head>
        <title>Sameer&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-black'>
        <section className='min-h-screen'>
          {/* navbar */}
          <nav className='py-10 mb-12 flex justify-between'>
            <Link href='/'><a><h1 className='text-3xl font-quickKiss dark:text-white'>Sameer</h1></a></Link>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl dark:text-white' onClick={()=>setDarkMode(!darkMode)}/></li>
              <a href='https://linkedin.com/in/-sameer/'><BsLinkedin className='text-2xl ml-5 rounded-md dark:text-white'/></a>
              <li><a className='bg-gradient-to-r from-cyan-500 to-purple-400 text-white px-4 py-1.5 rounded-2xl ml-5' href='https://drive.google.com/uc?export=download&id=16d1L187ZgMzFEe3TwRPcAPmBwRlh-s6R'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center'>
            <h2 className='text-5xl text-cyan-500'>Hi,</h2>
            <h2 className='text-2xl font-medium text-cyan-500'>I&apos;m Sameer</h2>
            <h2 className='text-xl text-gray-600 pt-5 dark:text-white'>Software Developer</h2>
            <h2 className='text-xl text-gray-600 dark:text-white'>and Machine Learning Engineer</h2>
          </div>
          <div className='flex justify-center my-10'>
            <div className='relative bg-gradient-to-b from-cyan-500 to bg-purple-400 rounded-full w-80 h-80 flex items-center overflow-hidden lg:h-90 lg:w-90'>
              <Image src={deved} layout="fill" objectFit='cover' />
            </div>
          </div>
        </section>
        <section>
          <div className='text-center md:max-w-3xl mx-auto py-10'>
            <h2 className='text-4xl text-gray-600 font-medium dark:text-white'>About me</h2>
            <p className='text-xl py-3 text-gray-600 dark:text-white'>
              I am an expert software developer capable of working with both the <span className='text-cyan-500'>front-end</span> and <span className='text-cyan-500'>backend</span> of applications.
              I create user-friendly, performant <span className='text-cyan-500'>web applications</span> that scale.
              I also do <span className='text-cyan-500'>UI/UX design</span> and have experience working with the <span className='text-cyan-500'>cloud</span>, 
              creating and deploying <span className='text-cyan-500'>machine learning</span> models, and <span className='text-cyan-500'>DevOps</span> pipelines.
              Currently pursuing my Bachelor of Computer Engineering degree at Memorial University of Newfoundland.
            </p>
          </div>
          <div className='text-center'>
            <h2 className='text-4xl text-gray-600 pt-10 pb-5 font-medium md:text-left dark:text-white'>Core Services Offered</h2>
            <div className='pt-2 md:flex justify-between'>
              <div className='shadow-lg p-12 rounded-xl m-8 md:my-8 md:ml-0 dark:bg-white'>
                <Image src={design} width={100} height={100}/>
                <h2 className='text-lg'>UI/UX Design</h2>
              </div>
              <div className='shadow-lg p-8 rounded-xl m-8 dark:bg-white'>
                <Image src={code} width={100} height={100} />
                <h2 className='text-lg'>Software Development</h2>
              </div>
              <div className='shadow-lg p-8 rounded-xl m-8 dark:bg-white'>
                <Image src={code} width={100} height={100} />
                <h2 className='text-lg'>Machine Learning</h2>
              </div>
            </div>
        </div>
        </section>
        <section>
          <div >
            <h3 className='text-4xl text-gray-600 mt-5 pt-10 pb-5 font-medium text-center md:text-left dark:text-white'>Work Experience</h3>
            <p className='text-xl py-3 text-gray-600 dark:text-white'>
              I am an expert software developer capable of working with both the <span className='text-cyan-500'>front-end</span> and <span className='text-cyan-500'>backend</span> of applications.
              I create user-friendly, performant <span className='text-cyan-500'>web applications</span> that scale.
              I also do <span className='text-cyan-500'>UI/UX design</span> and have experience working with the <span className='text-cyan-500'>cloud</span>, 
              creating and deploying <span className='text-cyan-500'>machine learning</span> models, and <span className='text-cyan-500'>DevOps</span> pipelines.
              Currently pursuing my Bachelor of Computer Engineering degree at Memorial University of Newfoundland.
            </p>
          </div>
          <div>
            <h3 className='text-4xl text-gray-600 mt-5 pt-10 pb-5 font-medium text-center md:text-left dark:text-white'>Projects</h3>
            <p className='text-xl py-3 text-gray-600 dark:text-white'>
              Below is a list of all the cool projects I have worked on in the past
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1}
              className="rounded-lg object-cover"
              width={"100%"}
              height={"100%"}
              layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2}
              className="rounded-lg object-cover"
              width={"100%"}
              height={"100%"}
              layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3}
              className="rounded-lg object-cover"
              width={"100%"}
              height={"100%"}
              layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4}
              className="rounded-lg object-cover"
              width={"100%"}
              height={"100%"}
              layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5}
              className="rounded-lg object-cover"
              width={"100%"}
              height={"100%"}
              layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3}
              className="rounded-lg object-cover"
              width={"100%"}
              height={"100%"}
              layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
