import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'

// Exporting the function/component called Home as a default
// A component is a JS func that returns some HTML(JSX)
export default function Home() {
  return (
    <div>
      <Head>
        <title>Sameer&apos;s Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          {/* navbar */}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Sameer</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-purple-400 text-white px-4 py-2 rounded-3xl ml-6' href='https://drive.google.com/uc?export=download&id=16d1L187ZgMzFEe3TwRPcAPmBwRlh-s6R'>Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>

      
    </div>
  )
}
